epochs: 1000
accelerator: cpu
devices: 1
accumulate_grad_batches: 1
precision: 32
check_val_every_n_epoch: ${algorithm.check_val_every_n_epoch}
fast_dev_run: False
matmul_precision: null
num_sanity_val_steps: 2
checkpointing: False
enable_progress_bar: True
gradient_clip_val: 0