defaults:
  - simulator: no_ml_mgn_simulator
  - optimizer: adamw
  - scheduler: standard
  - evaluator: ml_evaluator
  - _self_

dataset_return_type: torch_geometric

name: no_ml_mgn_torch_geometric
verbose: False
regression: False
check_val_every_n_epoch: 1
