name: hmpn_step_simulator
decoder:
  latent_dimension: 128
  regularization:
    dropout: 0.0
  tanh:
    enabled: True
    scale_factor: 0.1
    input_scale_factor: 0.1

gnn:
  name: hmpn_gnn
  latent_dimension: 128
  share_base: False
  base:
    assert_graph_shapes: False
    scatter_reduce: mean  # how to reduce the edge features for node updates, and the edge and node features for
    # global updates
    # Can be either a single operation or any list of the following: "mean", "sum", "min" or "max", "std".
    create_graph_copy: True  # whether to create a copy of the used graph before the forward pass or not
    stack:
      layer_norm: inner # which kind of layer normalization to use. null/None for no layer norm,
      # "outer" for layer norm around each full message passing step, "inner" for layer norm after each message
      num_steps: 15
      num_step_repeats: 1
      residual_connections: inner
      mlp:
        activation_function: leakyrelu
        num_layers: 1
        add_output_layer: False
        regularization:
          dropout: 0
          spectral_norm: False
          latent_normalization: null
    embedding:
      mlp:
        activation_function: leakyrelu
        num_layers: 1
        add_output_layer: False
        regularization:
          dropout: 0
          spectral_norm: False
          latent_normalization: null