name: dp_ml
wandb_name: dp_hard_v5_ml
root: ../datasets/mango/ml_dp_hard_v5.hdf5
z_pos_feature: False


train_dataset:
  root: ${dataset.root}
  step: False
  batch_size: 1
  initial_vel: zero  # choose between zero and constant
  dataset_size: null  # artificially reduce dataset size for debugging
  random_traj_selection: True
  min_context_size: 1
  max_context_size: 8
  min_target_size: 1
  max_target_size: 1
  material_properties: False
  material_properties_dim: 2
  time_subsampling: 1
  regression: ${algorithm.regression}


eval_dataset:
  root: ${dataset.root}
  step: False
  initial_vel: ${..train_dataset.initial_vel}
  dataset_size: null # artificially reduce dataset size for debugging
  random_traj_selection: False
  context_size: 4  # deterministic
  target_size: 16
  material_properties: ${..train_dataset.material_properties}
  material_properties_dim: 2
  time_subsampling: ${..train_dataset.time_subsampling}
  regression: ${algorithm.regression}