# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN  # needed for launcher to be used
  launcher:
    # launcher/cluster specific options
    partition: "gpu_h100"
    timeout_min: 2880 # in minutes, increase for your needs
    gres: gpu:1 # one gpu allocated
#    mem_per_gpu: 193300  # in MB
#    additional_parameters:
#      cpus-per-task: 4